"""empty message

Revision ID: 2d9594fc602d
Revises: 518dee2bcda0
Create Date: 2024-08-30 19:46:30.304276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9594fc602d'
down_revision = '518dee2bcda0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'project_id')
    # ### end Alembic commands ###
