"""empty message

Revision ID: 41ddf49e336f
Revises: 2d9594fc602d
Create Date: 2024-11-20 21:46:52.643724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ddf49e336f'
down_revision = '2d9594fc602d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_group_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_group_id_fkey', 'projects', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
