"""empty message

Revision ID: 473ee2eabca3
Revises: b070d3f84555
Create Date: 2024-08-10 18:29:49.428576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473ee2eabca3'
down_revision = 'b070d3f84555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
