"""empty message

Revision ID: 651ae78051d9
Revises: d9787affa31c
Create Date: 2024-08-22 13:51:03.018797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651ae78051d9'
down_revision = 'd9787affa31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_project_id_key', 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('groups_project_id_key', 'groups', ['project_id'])
    # ### end Alembic commands ###
