"""empty message

Revision ID: 6f9d68bf2541
Revises: f5964d34265c
Create Date: 2024-04-11 12:55:16.137471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9d68bf2541'
down_revision = 'f5964d34265c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
