"""empty message

Revision ID: d9787affa31c
Revises: 473ee2eabca3
Create Date: 2024-08-10 18:35:09.808735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9787affa31c'
down_revision = '473ee2eabca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'group_id')
    # ### end Alembic commands ###
