"""empty message

Revision ID: f5964d34265c
Revises: f26cfb576fce
Create Date: 2024-04-11 12:52:22.459771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5964d34265c'
down_revision = 'f26cfb576fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
